# Generated by Django 2.0 on 2020-10-20 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('chaptername', models.CharField(max_length=20, verbose_name='章节名称')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '小说章节表',
                'verbose_name_plural': '小说章节表',
                'db_table': 'novels_chapter',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('Collec_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
            ],
            options={
                'verbose_name': '小说收藏表',
                'verbose_name_plural': '小说收藏表',
                'db_table': 'novels_collection',
            },
        ),
        migrations.CreateModel(
            name='Hits',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('hits_time', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
            ],
            options={
                'verbose_name': '小说点赞表',
                'verbose_name_plural': '小说点赞表',
                'db_table': 'novels_hits',
            },
        ),
        migrations.CreateModel(
            name='Novels',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20, verbose_name='小说书名')),
                ('title', models.CharField(max_length=50, verbose_name='小说标题')),
                ('desc', models.TextField(verbose_name='概述')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('image', models.ImageField(upload_to='novels', verbose_name='小说图片')),
                ('status', models.SmallIntegerField(choices=[(0, '下线'), (1, '上线')], default=1, verbose_name='小说状态')),
                ('is_delete', models.SmallIntegerField(choices=[(0, '默认'), (1, '删除')], default=1, verbose_name='是否删除')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '小说表',
                'verbose_name_plural': '小说表',
                'db_table': 'novels',
            },
        ),
        migrations.CreateModel(
            name='NovelsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=30, verbose_name='小说类别名称')),
                ('logo', models.CharField(max_length=30, verbose_name='类别标识')),
                ('image', models.ImageField(upload_to='type', verbose_name='类别图片')),
                ('status', models.SmallIntegerField(choices=[(0, '禁用'), (1, '使用中')], default=1, verbose_name='类别状态')),
            ],
            options={
                'verbose_name': '小说类别表',
                'verbose_name_plural': '小说类别表',
                'db_table': 'novels_type',
            },
        ),
        migrations.CreateModel(
            name='ViceNovels',
            fields=[
                ('uid', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('hits', models.IntegerField(default=0, verbose_name='点击量')),
                ('collection', models.IntegerField(default=0, verbose_name='收藏量')),
                ('novels', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='novels.Novels')),
            ],
            options={
                'verbose_name': '小说副表',
                'verbose_name_plural': '小说副表',
                'db_table': 'novels_vice',
            },
        ),
        migrations.AddField(
            model_name='novels',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.NovelsType', verbose_name='小说类别'),
        ),
        migrations.AddField(
            model_name='hits',
            name='novels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.Novels'),
        ),
        migrations.AddField(
            model_name='hits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='novels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.Novels'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapter',
            name='novels',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='novels.Novels'),
        ),
    ]
