# Generated by Django 2.0 on 2020-10-20 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='小说图片')),
                ('index', models.SmallIntegerField(default=0, verbose_name='展示顺序')),
                ('novels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.Novels', verbose_name='小说书名')),
            ],
            options={
                'verbose_name': '首页推荐图',
                'verbose_name_plural': '首页推荐图',
                'db_table': 'index_banner',
            },
        ),
        migrations.AlterField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
