# Generated by Django 2.0 on 2020-10-22 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_auto_20201020_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='novels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.Novels'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='indexbanner',
            name='image',
            field=models.ImageField(upload_to='banner', verbose_name='小说推荐图片'),
        ),
    ]
