# Generated by Django 2.0 on 2020-10-27 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novels', '0003_auto_20201022_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBookrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapters_uid', models.IntegerField(verbose_name='章节id')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('is_delete', models.SmallIntegerField(choices=[(0, '默认'), (1, '删除')], default=1, verbose_name='是否删除')),
                ('novels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.Novels')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '我的书架表',
                'verbose_name_plural': '我的书架表',
                'db_table': 'mybookrack',
            },
        ),
        migrations.AlterField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
