# Generated by Django 2.0 on 2020-11-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201014_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_author',
            field=models.SmallIntegerField(choices=[(0, '普通用户'), (1, '作者')], default=0, verbose_name='是否是作者'),
        ),
    ]
